### ISSUE TITLE
EC2 Tagging

### ISSUE THREAD

**Issue by hostragon-hosting** [awslabs/ec2-scheduler#2]
I used "**CustomTagName**: scheduler:ec2-startstop" since all the instances has the "Name" tag.

Should it be "**scheduler**:ec2-startstop"?

i wish there is a pictorial guide on the tagging to help non-English speakers.

**Comment by neilwheeler** [comment]
If you use the names in the documentation the tag Key should be "scheduler:ec2-startstop" and the value should be "default" or "True" (or for a custom start/stop time a value in the format hhmm;hhmm;utc;days). 

If you want to change the tag Key after running the cloudformation template you can do so by adjusting the value in the DynamoDB table that it created. 

I hope that helps! I'm not the developer, but I went through the same exercise as you to set this up and found it a little confusing too!

Attached image shows the DynamoDB table with my tag name called "startstop". 
![2016-10-04 09_52_04-capture](https://cloud.githubusercontent.com/assets/22595070/19076933/9bdedc78-8a18-11e6-9307-aa5a75083372.png)

**Comment by groverlalit** [comment]
@neilwheeler Thanks for answering the question. 

 @hostragon-hosting  It should be "scheduler:ec2-startstop".
Thanks again.
