### ISSUE TITLE
EC2 Scheduler is not working

### ISSUE THREAD

**Issue by globaldatanet** [awslabs/ec2-scheduler#20]
I am running an instance in eu-central-1 and added the tag: "scheduler:ec2-startstop" with value "default". I set the DefaultDaysActive to "weekdays" , starttime to "0700" and stoptime to "1900". Unfortunately nothings happening.

<img width="1189" alt="bildschirmfoto 2018-02-04 um 22 41 57" src="https://user-images.githubusercontent.com/15118990/35782725-d9ce7b5a-09fc-11e8-9661-fda7d6b1f271.png">
<img width="1159" alt="bildschirmfoto 2018-02-04 um 22 42 18" src="https://user-images.githubusercontent.com/15118990/35782726-d9e5b784-09fc-11e8-9616-284a38e922a7.png">
<img width="1226" alt="bildschirmfoto 2018-02-04 um 22 42 44" src="https://user-images.githubusercontent.com/15118990/35782727-d9fd5ab0-09fc-11e8-95fd-a7f02587765d.png">

**Comment by arieleeuw** [comment]
https://aws.amazon.com/answers/infrastructure-management/instance-scheduler/
